version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=loopback
      - MARIADB_PASSWORD=lbbackend11.*
      - MARIADB_DATABASE=marketplace
